#!/bin/bash
# A script to call ..../prophet-sql-dump by crontab to dump dev-trunk-goldendb in the early mornings.
# dbs_to_dump="dev-tomcat-goldendb:prophet_bps"
dbs_to_dump="dev-trunk-goldendb:prophet dev-tomcat-goldendb:prophet_bps"
# dbs_to_dump="dev-trunk-goldendb dev-trunk-tomcatdb"
for db in $dbs_to_dump; do
    echo "-#-#-#-#-#-#-#-#-# $db #-#-#-#-#-#-#-#-#-#-"

    # According to TeamCity: dev-trunk-goldendb is triggered at 23:10 (CST) daily
    dump_dir=/home/mwilber/projects/prophet-data/${db/:/_}-daily
    dump_file="${dump_dir}/${db/:/_}-$(date +\%Y\%m\%d-\%H\%M).dump"
    link_file="$(dirname $(dirname $dump_file))/${db/:/_}-daily-latest.dump"

    # Make sure the directory exists
    mkdir -p ${dump_dir}

    # Clean out older files
    # find ${dev_trunk_golden_dump_dir} -mtime +20 -exec rm {} \;

    # To let the authorization be automated put the password in ~/.pgpass
    ~mwilber/.be-env/prophet/prophet-sql-dump ${db} "${dump_file}"

    if [ $? -eq 0 ] && [ -s "${dump_file}" ]; then
        echo "Update link - ${link_file}"
        rm -f "${link_file}"
        ln -s "${dump_file}" "${link_file}"
    else
        echo "Link not updated based on failed sql dump"
    fi
done

