#!/bin/bash

###############################################################################
# Usage
###############################################################################
usage()
{
    echo
	echo "Destroy and recreate a database and restore from a local file"
	echo
	echo "Usage: $self <database_name> <local_dump_file>"
	echo "   <database_name> "
	echo "   <local_dump_file> "
	echo "   db_host and db_user may be set in order to affect another host/user"
	exit 1;
}


# /////////////////// Main

if [ $# -lt 2 ]; then
	echo "Both a database and a local dump file need to be specified."
	usage
fi

database_name=$1
local_dump_file=$2
db_user=${db_user:-prophet}
db_host=${db_host:-localhost}
echo "$(date +%T)  Dropping existing databases"
echo "           Host: ${db_host}"
echo "           Databases: ${database_name}, ${database_name}_test"
read -t 10 -p "Hit any key to continue immediately or Ctrl-C within 10 seconds to cancel..."
echo Done

# Drop the existing database before restoring
echo "dropdb --if-exists -h ${db_host} -U $db_user $database_name"
dropdb --if-exists -h ${db_host} -U $db_user $database_name
if [ $? != 0 ]; then
  echo ""
  echo "ERROR: .... Dropping failed! Exiting....";
  exit;
fi

# Drop the prophet_test database, if it exists
echo "dropdb --if-exists --host ${db_host} --username $db_user ${database_name}_test"
dropdb --if-exists --host ${db_host} --username $db_user ${database_name}_test
if [ $? != 0 ]; then
  echo ""
  echo "ERROR: .... Dropping failed! Exiting....";
  exit;
fi

echo "createdb --host ${db_host} --username $db_user $database_name"
createdb --host ${db_host} --username $db_user $database_name

echo ""
echo "Beginning restore of dump file [$local_dump_file] to database [$database_name]"
echo "pg_restore --verbose --host ${db_host} --username $db_user --dbname $database_name $local_dump_file"
pg_restore --verbose --host ${db_host} --username $db_user --dbname $database_name $local_dump_file

echo ""
echo "VACUUM database [$database_name]"
echo "vacuumdb --verbose --host ${db_host} --username $db_user --dbname $database_name"
vacuumdb --verbose --host ${db_host} --username $db_user --dbname $database_name
