#!/usr/bin/env bash

###############################################################################
# Usage
###############################################################################
usage()
{
    echo
	echo "Copy an existing data dump locally"
	echo
	echo "Usage: $self <host>[:<dbname>] [destinationFile]"
    echo "  host must be specified"
    echo "  dbname can be added if it is not 'prophet'  dev-trunk-golden:prophet_bps"
    echo "  destinationFile defaults to <host>_<dbname>_<date>.dump if not specified"
    echo 
	echo
	exit 1;
}


# /////////////////// Main

if [ $# -lt 1 ]; then
	echo "At least a database host needs to be specified (i.e. neptune -> dev-neptunedb)"
	usage
fi

# Handle host:dbname pattern (default dbname to prophet if none specified)
dbhost=${1%:*}
dbname=${1#*:}
if [ "$dbname" = "$dbhost" ]; then
    dbname=prophet
fi
#
# echo "<$dbhost>:<$dbname>"
# if [[ $dbhost != dev*db ]] && [[ $dbhost != tgt*db ]] && [[ $dbhost != stable*db ]]; then
#   dbhost=dev-${dbhost}db
# else
#   echo "Using straight up host name"
# fi

#destinationDir=$dbHost
destinationFile=${2:-${dbhost}_${dbname}_`date +%F`.dump}

if [ -r $destinationFile ]; then
	echo "WARN: $destinationFile already exists. It will be overwritten!"
#	rm -fv $destinationDir/*
#else
#	echo "Creating dir: $destinationDir"
#	mkdir -p $destinationDir;
fi

#pushd $destinationDir > /dev/null
#debug echo PWD=`pwd`

echo "Beginning dump of '$dbname' from '$dbhost'"
echo "pg_dump -v -F c -U prophet -h $dbhost $dbname > $destinationFile"
pg_dump --verbose --format=custom --username prophet --host $dbhost $dbname > $destinationFile
status=$?
if [ $status -eq 0 ];then
    echo "COMPLETED: Dump of ${dbhost}:${dbname} to ${destinationFile}"
else
    echo "FAILED: Dump of ${dbhost}:${dbname} to ${destinationFile}"
fi

exit $status
