#!/usr/bin/env bash

export PROPHET_ANALYTICS_SERVER_OPTS=-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n
prophet_home=/Users/mwilber/projects/pht/pht2
analytics_version=1.5.8
analytics_home=$prophet_home/tools/prophet-analytics-server-${analytics_version}

${analytics_home}/bin/prophet-analytics-server \
  $PROPHET_ANALYTICS_SERVER_OPTS \
  --spring.profiles.active=managed \
  --prophet.etc=${prophet_home}/etc \
  --spring.config.location=${analytics_home}/config/ \
  --cluster.managed-mode=true \
  --logging.path=${prophet_home}/logs \
  --spring.datasource.host=dev-trunk-infoprintdb.bybaxter.com \
  --spring.datasource.databaseName=prophet_mt \
  --spring.datasource.username=prophet \
  --spring.datasource.password=prophet \
  --spring.datasource.port=5432 \
  --spring.datasource.initialSize=1 \
  --spring.datasource.minIdle=1 \
  --spring.datasource.maxIdle=45 \
  --spring.datasource.maxActive=45 \
  --spring.datasource.maxWait=120000 \
  --geocoder.host=osrm.bybaxter.com \
  --geocoder.port=8989 \
  --travelcalc.host=osrm.bybaxter.com \
  --travelcalc.port=8080
